export default {
    "index": "Introduction",
    "ArrayAndHashing": "Array and Hashing",
    "Sorting": "Sorting",
    "Stack": "Stack",
    "TwoPointers": "Two Pointers",
    "SlidingWindow": "Sliding Window",
    "BinarySearch": "Binary Search",
    "LinkedList": "Linked List",
    "Trees": "Trees",
    "BackTracking": "Backtracking",
    "PriorityQueue": "Priority Queue",
    "---" : {title:"Advanced",type: "separator"},
    "Intervals": "Intervals",
    "Greedy": "Greedy",
    "Graphs": "Graphs",
    "AdvancedGraphs": "Advanced Graphs",
    "1D-DP": "1D - DP",
    "2D-DP": "2D - DP",
    "BitManipulation": "Bit Manipulation",
    "Maths": "Maths",
    "Tries": "Tries"
};