export default {   
    '*' : {type: "page",display: "navbarHidden"},
    index: {title: "Home",display: "hidden"},
    fundamentals: "Fundamentals",
    generation: "Generation",
    storage: "Storage",
    ingestion: "Ingestion",
    transformation: "Transformation",
    serving: "Serving",
    security: "Security",
    management: "Management",
    dataops: "DataOps",
    architecture: "Architecture",
    orchestration: "Orchestration",
    programming: "Programming",
    projects: "Projects",
    casestudy: "Case Studies",
    resources: "Resources",
    about: {title: "About",display: "visible"}    
}; 